-- RestLink USSD GW full schema (squashed baseline 2026-08-05).
-- Idempotent CREATE IF NOT EXISTS — Flyway on startup.
-- PostgreSQL; H2 MODE=PostgreSQL for lab.
--
-- Policy: single V1 baseline. Old V2–V4 history was removed; wipe lab H2 / reset
-- flyway_schema_history on any existing DB before first boot with this file.

-- ── Short-code routing ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ussd_short_code (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  short_code VARCHAR(32) NOT NULL UNIQUE,
  rule_type VARCHAR(16) NOT NULL,
  as_url VARCHAR(512) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  tenant_id VARCHAR(128),
  network_id INT NOT NULL DEFAULT 0
);

-- ── Tenants / portal users ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ussd_tenant (
  tenant_id VARCHAR(128) PRIMARY KEY,
  display_name VARCHAR(256),
  network_id INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  http_api_key VARCHAR(256),
  smpp_system_id VARCHAR(128),
  smpp_password VARCHAR(256),
  as_callback_base VARCHAR(1024),
  max_tps INT NOT NULL DEFAULT 50,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ussd_admin_user (
  username VARCHAR(64) PRIMARY KEY,
  password_hash VARCHAR(256) NOT NULL,
  role VARCHAR(16) NOT NULL,
  tenant_id VARCHAR(128),
  display_name VARCHAR(256),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ussd_tenant_network ON ussd_tenant(network_id);
CREATE INDEX IF NOT EXISTS idx_ussd_user_tenant ON ussd_admin_user(tenant_id);

-- ── CDR (OTA-shaped async / PostgreSQL-friendly) ─────────────────────────────

CREATE TABLE IF NOT EXISTS ussd_cdr (
  id                UUID PRIMARY KEY,
  recorded_at       TIMESTAMP WITH TIME ZONE NOT NULL,
  correlation_id    VARCHAR(128) NOT NULL,
  phase             VARCHAR(32)  NOT NULL,
  status            VARCHAR(64)  NOT NULL,
  msisdn            VARCHAR(32),
  short_code        VARCHAR(32),
  detail            VARCHAR(1024),
  network_id        INT,
  tenant_id         VARCHAR(128),
  origination_type  VARCHAR(32),
  csv_line          VARCHAR(4000) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ussd_cdr_recorded ON ussd_cdr (recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_ussd_cdr_corr ON ussd_cdr (correlation_id);
CREATE INDEX IF NOT EXISTS idx_ussd_cdr_msisdn ON ussd_cdr (msisdn);
CREATE INDEX IF NOT EXISTS idx_ussd_cdr_tenant ON ussd_cdr (tenant_id);
CREATE INDEX IF NOT EXISTS idx_ussd_cdr_tenant_recorded ON ussd_cdr (tenant_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_ussd_cdr_msisdn_recorded ON ussd_cdr (msisdn, recorded_at DESC);

-- ── KV config ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ussd_config (
  config_key VARCHAR(128) PRIMARY KEY,
  config_value VARCHAR(1024) NOT NULL
);
