-- Allow multiple short-code rules that share short_code when app_username differs.
-- V1 UNIQUE(short_code) alone blocked a second app-user binding.
-- Unbound / blank app_username is stored as '' so composite UNIQUE works on H2 + PostgreSQL
-- (NULL is distinct in UNIQUE and would allow duplicate unbound rows).

UPDATE ussd_short_code
   SET app_username = ''
 WHERE app_username IS NULL OR TRIM(app_username) = '';

CREATE TABLE ussd_short_code_v8 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  short_code VARCHAR(32) NOT NULL,
  rule_type VARCHAR(16) NOT NULL,
  as_url VARCHAR(512) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  tenant_id VARCHAR(128),
  network_id INT NOT NULL DEFAULT 0,
  mark BOOLEAN NOT NULL DEFAULT FALSE,
  app_username VARCHAR(64) NOT NULL DEFAULT '',
  CONSTRAINT uk_ussd_short_code_app UNIQUE (short_code, app_username)
);

INSERT INTO ussd_short_code_v8 (
    short_code, rule_type, as_url, enabled, tenant_id, network_id, mark, app_username)
SELECT
    short_code,
    rule_type,
    as_url,
    enabled,
    tenant_id,
    network_id,
    CASE WHEN mark IS NULL THEN FALSE ELSE mark END,
    COALESCE(NULLIF(TRIM(app_username), ''), '')
FROM ussd_short_code;

DROP TABLE ussd_short_code;

ALTER TABLE ussd_short_code_v8 RENAME TO ussd_short_code;
